In [3]:
import numpy as np
from simplex import simplex, rationals

In [16]:
# A = np.array([[1,3,0,4,1,1,0,0],[1,2,0,-3,1,0,1,0],[-1,-4,3,0,0,0,0,1]])
# b = np.array([2,2,1])
# c = np.array([0,0,0,0,0,1,1,1])

A = np.array([[1,1,-1,0,0,1,0,0],[-1,1,0,-1,0,0,1,0],[0,1,0,0,1,0,0,1]])
b = np.array([2,1,3])
c = np.array([0,0,0,0,0,1,1,1])

# A = np.array([[1,3,0,4,1],[1,2,0,-3,1],[-1,-4,3,0,0]])
# b = np.array([2,2,1])
# c = np.array([2,3,3,1,-2])

# A = np.array([[2,0,0,4],[1,2,0,-3],[-1,-4,3,0]])
# b = np.array([1,2,1])
# c = np.array([-2,3,3,1])

In [34]:
invA = np.linalg.inv(A[:, [0,1,2]])
col_t = np.dot(invA, A[:, 4])
identity_delta = np.eye(3, 3)
identity_delta[:, 1] = col_t
invA, A[:, 4], col_t
# A[:, [0,4,2]], np.dot(A[:, [0,1,2]], identity_delta)
A[:, [0,1,2]], invA, A[:, 4]

(array([[ 1,  1, -1],
        [-1,  1,  0],
        [ 0,  1,  0]]),
 array([[ 0., -1.,  1.],
        [ 0.,  0.,  1.],
        [-1., -1.,  2.]]),
 array([0, 0, 1]))

In [14]:
counter = 0
basis = [5,6,7]
while True:
    b_bar = np.dot(np.linalg.inv(A[:, basis]), b)
    y_bar = np.dot(c[basis], np.linalg.inv(A[:, basis]))
    c_bar = c - np.dot(y_bar, A)
    if all(c_bar>=0):
        x_bar = list(b_bar)
        x_bar += (A.shape[1]-len(b_bar))*[0]
        print(f"The {counter+1}th iteration gives the optimal result of\n\tc_bar={c_bar}\n\tx={x_bar}\n\ty={y_bar}\n\tB={[i+1 for i in basis]}")
        break
    t = np.argmax(c_bar<0) # choose the first negative number (smallest index)
    # t = np.argmin(c_bar) # choose the most negative number
    At_bar = np.dot(np.linalg.inv(A[:, basis]), A[:, t])
    if all(At_bar<=0):
        print(f"The {counter+1}th iteration gives the unbounded certificate")
        break
    min_val = float("inf")
    r = 0
    for i in range(len(b_bar)):
        if At_bar[i] <= 0: continue
        if b_bar[i]/At_bar[i] < min_val:
            min_val = b_bar[i]/At_bar[i]
            r = i
    
    print(f"Iteration {counter+1}:\n\tB={[i+1 for i in basis]}\n\tc_bar={c_bar}\n\tb_bar={b_bar}\n\tAt_bar={At_bar}\n\ty_bar={y_bar}\n")

    basis[r] = t

    counter += 1

Iteration 1:
	B=[6, 7, 8]
	c_bar=[ 0. -3.  1.  1. -1.  0.  0.  0.]
	b_bar=[2. 1. 3.]
	At_bar=[1. 1. 1.]
	y_bar=[1. 1. 1.]

Iteration 2:
	B=[6, 2, 8]
	c_bar=[-3.  0.  1. -2. -1.  0.  3.  0.]
	b_bar=[1. 1. 2.]
	At_bar=[ 2. -1.  1.]
	y_bar=[ 1. -2.  1.]

Iteration 3:
	B=[1, 2, 8]
	c_bar=[ 0.   0.  -0.5 -0.5 -1.   1.5  1.5  0. ]
	b_bar=[0.5 1.5 1.5]
	At_bar=[-0.5 -0.5  0.5]
	y_bar=[-0.5 -0.5  1. ]

The 4th iteration gives the optimal result of
	c_bar=[0. 0. 0. 0. 0. 1. 1. 1.]
	x=[2.0, 3.0, 3.0, 0, 0, 0, 0, 0]
	y=[0. 0. 0.]
	B=[1, 2, 3]


## API Generated

In [15]:
MAX = False
# m = np.array(rationals([[1,3,0,4,1,1,0,0,2],[1,2,0,-3,1,0,1,0,2],[-1,-4,3,0,0,0,0,1,1]]))
m = np.array(rationals([[1,1,-1,0,0,1,0,0,2],[-1,1,0,-1,0,0,1,0,1],[0,1,0,0,1,0,0,1,3]]))
c_name = [f'x{i+1}' for i in range(len(c))]
base_name = ['x6', 'x7', 'x8']
base = np.array([c[c_name.index(e)] for e in base_name])

simplex(MAX, c, c_name, m, base, base_name)

             c  0  0  0  0  0  1  1  1            
base base_name x1 x2 x3 x4 x5 x6 x7 x8 const theta
   1        x6  1  1 -1  0  0  1  0  0     2     2
   1        x7 -1  1  0 -1  0  0  1  0     1     1
   1        x8  0  1  0  0  1  0  0  1     3     3
            pi  0  3 -1 -1  1  1  1  1     6      
        c - pi  0 -3  1  1 -1  0  0  0            
pivot(col = x2, row = x7)
--------------------------------------------------------------------------------
             c  0  0  0  0  0  1  1  1            
base base_name x1 x2 x3 x4 x5 x6 x7 x8 const theta
   1        x6  2  0 -1  1  0  1 -1  0     1   1/2
   0        x2 -1  1  0 -1  0  0  1  0     1   inf
   1        x8  1  0  0  1  1  0 -1  1     2     2
            pi  3  0 -1  2  1  1 -2  1     3      
        c - pi -3  0  1 -2 -1  0  3  0            
pivot(col = x1, row = x6)
--------------------------------------------------------------------------------
             c  0  0    0    0  0    1    1  1            
base base_nam